### ISSUE TITLE
Server side events fails with Node 18

### ISSUE THREAD

**Issue by ovdahlberg** [RivercodeAB/facebook-conversion-api-nextjs#14]
Hi,

Seems like all server side events fails with Node 18: **TypeError: object2 is not iterable**

If anyone have time to take a look at it, it's much appreciated.

Otherwise I will check as soon as I have some time over.

**Comment by tomryanx** [comment]
Same problem. Looks like there's another issue about this too.. (#13)

**Comment by zachsitka** [comment]
We are seeing this in production. Issue started on March 21st. Using version 4.1.0.

**Comment by ovdahlberg** [comment]
Hi @tomryanx and @zachsitka!

This should be fixed in 4.3.1. Please try and see if it works for you now :)
