### ISSUE TITLE
Components module not found

### ISSUE THREAD

**Issue by jeremylynch** [RivercodeAB/facebook-conversion-api-nextjs#6]
Great project! Thankyou. 

I am getting the below error when trying to import the `FBPixelProvider`. 
```js
import { FBPixelProvider } from '@rivercode/facebook-conversion-api-nextjs/components';
```

```
Module not found: Can't resolve '@rivercode/facebook-conversion-api-nextjs/handlers'
```

**Comment by ovdahlberg** [comment]
Hi @jeremylynch! What version of Next.is are you using? Typescript or regular JS?

**Comment by jeremylynch** [comment]
We are using nextjs 11.1 and JavaScript (no typescript)

**Comment by ovdahlberg** [comment]
Could you try to update the package to version 2.0.5 and see if that fix the issue? @jeremylynch

**Comment by jeremylynch** [comment]
Just upgraded to latest (2.0.6) and issue is still occurring

**Comment by jeremylynch** [comment]
Interestingly, upgrading from Nextjs 11.1.2 to 11.1.3-canary.104 fixed the issue! 

I also should have mentioned I am using preact, taking preact away also fixed the problem (but now not necessary after upgrading to nextjs 11.1.3-canary.104).
